"""empty message

Revision ID: ad2f0809eab5
Revises: 127be3fb000
Create Date: 2016-05-10 21:47:05.922211

"""

# revision identifiers, used by Alembic.
revision = 'ad2f0809eab5'
down_revision = '127be3fb000'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_post',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(length=3000), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_table('news_post')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_post',
    sa.Column('text', sa.VARCHAR(length=3000), nullable=False),
    sa.PrimaryKeyConstraint('text')
    )
    op.drop_table('my_post')
    ### end Alembic commands ###
